import { Job } from "./types";

export const seedJobs: Job[] = [
  {
    id: "1042",
    reqCode: "REQ-1042",
    title: "Senior Backend Engineer",
    company: "Northwind Systems",
    location: "Austin, TX",
    locationType: "Hybrid",
    type: "Full-time",
    category: "Engineering",
    salaryMin: 145000,
    salaryMax: 180000,
    postedAt: "2026-07-01",
    closesAt: "2026-08-01",
    description:
      "Own the services that route millions of payments a day. You'll work close to the database, close to the money, and close to the on-call rotation.",
    responsibilities: [
      "Design and maintain high-throughput payment services in Go",
      "Set the pace for schema migrations across three teams",
      "Pair with SRE on incident response and postmortems",
    ],
    requirements: [
      "5+ years building backend systems in production",
      "Comfortable with Postgres internals and query planning",
      "Has carried a pager before and didn't hate it",
    ],
  },
  {
    id: "1043",
    reqCode: "REQ-1043",
    title: "Product Designer",
    company: "Fieldnote Studio",
    location: "Remote",
    locationType: "Remote",
    type: "Full-time",
    category: "Design",
    salaryMin: 110000,
    salaryMax: 140000,
    postedAt: "2026-07-05",
    closesAt: "2026-07-28",
    description:
      "Fieldnote makes tools for agricultural cooperatives. You'll design for people checking a screen between tractor runs, not people staring at a dashboard all day.",
    responsibilities: [
      "Run field research with co-op members across three states",
      "Ship low-bandwidth, high-clarity interfaces",
      "Maintain the shared component library in Figma",
    ],
    requirements: [
      "Portfolio showing systems thinking, not just screens",
      "Experience designing for low-connectivity or offline-first use",
    ],
  },
  {
    id: "1044",
    reqCode: "REQ-1044",
    title: "DevOps / Platform Engineer",
    company: "Cinderloop",
    location: "Remote",
    locationType: "Remote",
    type: "Contract",
    category: "Engineering",
    salaryMin: 90,
    salaryMax: 130,
    postedAt: "2026-06-28",
    closesAt: "2026-07-20",
    description:
      "Six-month contract to migrate a mid-size fleet from self-managed Kubernetes to a leaner, cheaper setup without a weekend of downtime.",
    responsibilities: [
      "Audit current cluster spend and cut it by a third",
      "Write the runbooks the next person will actually read",
      "Pair with two junior engineers along the way",
    ],
    requirements: [
      "Has done at least one real cluster migration, not just a lab exercise",
      "Terraform and GitHub Actions fluency",
    ],
  },
  {
    id: "1045",
    reqCode: "REQ-1045",
    title: "Customer Support Lead",
    company: "Harborline",
    location: "Portland, OR",
    locationType: "On-site",
    type: "Full-time",
    category: "Support",
    salaryMin: 70000,
    salaryMax: 85000,
    postedAt: "2026-07-08",
    closesAt: "2026-08-05",
    description:
      "Lead a support team of six for a small marine-logistics company. You'll set the tone for how we talk to boat owners who are, often, having a bad day.",
    responsibilities: [
      "Coach a team of six support specialists",
      "Rebuild the macros library from scratch",
      "Report weekly on ticket trends to the ops team",
    ],
    requirements: [
      "2+ years leading a support or success team",
      "Written communication that's warm but not saccharine",
    ],
  },
  {
    id: "1046",
    reqCode: "REQ-1046",
    title: "Data Analyst, Marketing",
    company: "Cutlass Media",
    location: "Chicago, IL",
    locationType: "Hybrid",
    type: "Full-time",
    category: "Data",
    salaryMin: 85000,
    salaryMax: 105000,
    postedAt: "2026-07-03",
    closesAt: "2026-07-31",
    description:
      "Turn campaign spend into a story the CMO can act on. You'll live in SQL and dashboards, but your job is the sentence at the top of the slide.",
    responsibilities: [
      "Build and maintain attribution models across paid channels",
      "Present findings directly to marketing leadership",
      "Partner with the data engineering team on pipeline requests",
    ],
    requirements: [
      "3+ years in marketing or growth analytics",
      "Strong SQL; light Python for the rest",
    ],
  },
  {
    id: "1047",
    reqCode: "REQ-1047",
    title: "Frontend Engineer (React)",
    company: "Northwind Systems",
    location: "Remote",
    locationType: "Remote",
    type: "Full-time",
    category: "Engineering",
    salaryMin: 120000,
    salaryMax: 155000,
    postedAt: "2026-06-30",
    closesAt: "2026-07-25",
    description:
      "Rebuild the merchant dashboard that eight thousand small businesses check every morning. Performance and clarity matter more than novelty here.",
    responsibilities: [
      "Own the merchant dashboard's component architecture",
      "Cut time-to-interactive on the mobile view",
      "Work directly with three merchant advisory customers",
    ],
    requirements: [
      "Strong React and TypeScript fundamentals",
      "Has shipped something used daily by non-technical people",
    ],
  },
  {
    id: "1048",
    reqCode: "REQ-1048",
    title: "Marketing Intern",
    company: "Fieldnote Studio",
    location: "Remote",
    locationType: "Remote",
    type: "Internship",
    category: "Marketing",
    salaryMin: 20,
    salaryMax: 24,
    postedAt: "2026-07-06",
    closesAt: "2026-07-22",
    description:
      "A ten-week paid internship writing field stories from co-op members and turning them into newsletter content people actually open.",
    responsibilities: [
      "Interview co-op members and draft short profiles",
      "Assist with the monthly newsletter calendar",
    ],
    requirements: [
      "Currently enrolled in a relevant program, or recently graduated",
      "Writing samples on request",
    ],
  },
  {
    id: "1049",
    reqCode: "REQ-1049",
    title: "Site Reliability Engineer",
    company: "Cinderloop",
    location: "Denver, CO",
    locationType: "Hybrid",
    type: "Full-time",
    category: "Engineering",
    salaryMin: 135000,
    salaryMax: 165000,
    postedAt: "2026-07-09",
    closesAt: "2026-08-10",
    description:
      "Keep a fleet of edge caches humming across eleven regions. You'll spend more time on error budgets than firefighting once the first quarter is done.",
    responsibilities: [
      "Define and track SLOs across core services",
      "Reduce alert noise by triaging the current on-call load",
      "Build tooling for capacity forecasting",
    ],
    requirements: [
      "Experience with distributed systems at scale",
      "Comfortable saying no to a launch that isn't ready",
    ],
  },
  {
    id: "1050",
    reqCode: "REQ-1050",
    title: "Bookkeeper, Part-Time",
    company: "Harborline",
    location: "Portland, OR",
    locationType: "On-site",
    type: "Part-time",
    category: "Finance",
    salaryMin: 28,
    salaryMax: 35,
    postedAt: "2026-06-25",
    closesAt: "2026-07-18",
    description:
      "Twenty hours a week keeping the books straight for a small logistics operation. No surprises, just steady, careful work.",
    responsibilities: [
      "Reconcile accounts payable and receivable weekly",
      "Prepare monthly reports for the owner",
    ],
    requirements: [
      "2+ years of bookkeeping experience",
      "Comfortable with QuickBooks",
    ],
  },
  {
    id: "1051",
    reqCode: "REQ-1051",
    title: "Data Engineer",
    company: "Cutlass Media",
    location: "Remote",
    locationType: "Remote",
    type: "Contract",
    category: "Data",
    salaryMin: 95,
    salaryMax: 120,
    postedAt: "2026-07-02",
    closesAt: "2026-07-27",
    description:
      "Four-month contract to build the ingestion pipeline our analysts have been asking for since Q1. Clean handoff to a full-time hire expected at the end.",
    responsibilities: [
      "Design a pipeline pulling from six ad-platform APIs",
      "Document decisions for the analyst who inherits this",
    ],
    requirements: [
      "Experience with dbt and a modern warehouse (Snowflake or BigQuery)",
      "Has handed off a project cleanly before",
    ],
  },
];
